version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - '/mnt/data/dbdata/mysql/scott:/var/lib/mysql'
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=scott
        - MYSQL_USER=scott_dev
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # command: mysqld --lower_case_table_names=1 --skip-ssl
    command: mysqld --lower_case_table_names=1

  scott.api:
    container_name: scott.api
    image: scottpy:latest
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - SERVER_PORT=5000
      - SERVER_TYPE=dev
      - DATABASE_SERVER=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=scott
      - DATABASE_USER=scott_dev
      - DATABASE_PASSWD=${MYSQL_PASSWORD}
